export const rescueGuides = {
  avgolemono: { title: 'Curdled avgolemono / egg-lemon sauce', actions: ['Take the sauce off heat immediately.', 'Blend with 1-2 tbsp ice water or cold broth to cool it quickly and smooth small curds. Use an immersion blender with its head submerged to avoid splashing.', 'Alternatively, whisk a fresh pasteurized yolk with cold water in a clean bowl, then gradually whisk in the cooled sauce to rebuild the emulsion.'], science: 'Egg yolk proteins denature and aggregate under excessive heat, often around or above 70°C depending on dilution and acidity. Rapid cooling stops further cooking; shearing can smooth small curds and help disperse fat, but cannot reverse protein coagulation.', caution: 'Use pasteurized yolk for this off-heat rescue. Severely scrambled sauce may need replacing; restoring texture does not make improperly stored egg sauce safe.' },
  bechamel_lumpy: { title: 'Lumpy / separated béchamel', actions: ['Take the béchamel off heat and whisk vigorously.', 'Pass it through a fine mesh sieve or use an immersion blender with its head submerged to smooth lumps.', 'Whisk in a splash of warm milk a little at a time until smooth.'], science: 'Flour clumps can trap dry starch inside a hydrated outer layer. Whisking and blending break up clumps; added milk loosens the starch-thickened sauce and helps redistribute separated fat.', caution: 'Avoid splashing hot sauce or blending it in a sealed vessel. If it is scorched, do not blend in the burnt layer.' },
  moussaka_watery: { title: 'Watery moussaka / pastitsio', actions: ['Carefully decant or spoon off excess pooled moisture without disturbing the layers.', 'Bake uncovered for another 10-15 minutes at the recipe temperature, watching the topping for over-browning.', 'Rest strictly 20-30 minutes before slicing so the layers can set.'], science: 'Uncovered baking evaporates excess moisture. Starches gelatinize during cooking; resting lets the cooked starch-thickened layers cool and firm up, making cleaner slices.', caution: 'Extra baking time is a texture adjustment, not proof that raw meat or egg layers are safely cooked.' },
  dry_meat: { title: 'Dry / tough roast lamb or meat', actions: ['Stop roasting and slice the cooked meat thinly across the grain.', 'Prepare warm seasoned stock with olive oil, lemon, and oregano.', 'Steep the slices gently in the warm stock, then serve with some of the liquid. Avoid boiling or further drying the meat.'], science: 'Overcooking contracts muscle proteins and drives out moisture. Cutting across the grain shortens the fibers; stock and olive oil improve perceived juiciness but cannot undo protein contraction.', caution: 'This guide is for cooked, dried-out meat. Tough connective-tissue-rich cuts may need a different cooking method; added stock does not make undercooked or improperly stored meat safe.' },
  burnt_garlic: { title: 'Burnt / scorched garlic in oil', actions: ['Take the pan off heat immediately.', 'Discard the scorched garlic and all of the affected oil; do not pour hot oil down the drain.', 'Once safe to handle, wipe the pan clean and restart with fresh oil and garlic over gentler heat.'], science: 'Garlic sulfur compounds, including compounds derived from allicin, change during heating. Scorching creates bitter, acrid flavors that spread through the oil base; removing only the garlic pieces will not remove that flavor.', caution: 'Let hot oil cool before disposal and keep water away from hot oil. Do not try to mask the burnt flavor.' },
  emulsion: { title: 'Split sauce / broken emulsion', actions: ['Take the sauce off heat. Do not add more fat yet.', 'For vinaigrette, whisk a little mustard and water in a clean bowl, then slowly whisk in the separated dressing.', 'For mayonnaise or hollandaise, start a fresh small emulsion in a clean bowl and incorporate the broken sauce a teaspoon at a time. Use pasteurized egg where the method calls for raw egg; do not try to re-emulsify curdled egg solids.'], science: 'An emulsion needs a continuous water phase and enough emulsifier to keep fat droplets dispersed. Too much fat at once or excess heat can destabilize it.', caution: 'Restoring texture does not make improperly stored egg sauces safe.' },
  salt: { title: 'Too salty', actions: ['Stop reducing and stop adding salt.', 'Dilute with unsalted liquid or add an unsalted batch of the same dish. For a solid dish, serve smaller portions with an unsalted side.', 'Use a small amount of acid or fat only to balance perception after dilution, tasting a separate spoonful first.'], science: 'Dilution reduces salt concentration. Acid and fat can balance flavor but do not remove sodium. A potato absorbs salty liquid; it does not selectively extract salt.', caution: 'Do not keep reducing the sauce after dilution: salt concentration rises again.' },
  scorch: { title: 'Scorched pot bottom', actions: ['Turn off the heat. Transfer the unburnt upper layer into a clean pot without stirring or scraping the bottom.', 'Taste a cooled spoonful. If only mildly affected, add fresh unsalted liquid and a little compatible fat or fresh herbs as a flavor harmonizer.', 'If the burnt flavor persists throughout, discard the affected dish and restart.'], science: 'Scraping disperses charred particles and bitter compounds through the food. Decanting limits their spread; seasoning cannot reverse burning.', caution: 'Never blend the scorched layer into the dish to hide it.' },
  sear: { title: 'Soggy pan / steaming instead of searing', actions: ['Remove some food and work in smaller batches.', 'Let pooled moisture evaporate in a suitable pan, then pat the next batch dry before adding it.', 'Preheat appropriately for the cookware and resume cooking with space between pieces. Avoid overheating nonstick pans.'], science: 'Evaporation consumes energy and a wet surface resists browning. A less crowded, drier surface can reach browning temperatures.', caution: 'Browning is not a substitute for checking the required internal temperature.' },
  acid: { title: 'Too acidic', actions: ['Test a spoonful with a little compatible fat or unsalted base.', 'Dilute the batch or add a small amount of sweetness, tasting between additions.', 'Avoid blindly adding baking soda: it can foam vigorously and leave a soapy taste.'], science: 'Dilution lowers acid concentration. Fat and sweetness change flavor balance without reliably changing acidity.', caution: 'Do not alter acid ratios in a canning or preservation recipe.' },
  spice: { title: 'Too spicy', actions: ['Add more unspiced base or split the batch and dilute each half.', 'If appropriate, stir in dairy or a compatible fat-containing ingredient; check dietary needs first.', 'Serve with plain rice, bread, or another neutral side. Additions balance heat rather than removing it.'], science: 'Capsaicin associates with fat; dairy proteins can help disperse it. Water alone does little to relieve its perceived heat.', caution: 'Taste cooled small samples; do not add more hot spices while adjusting.' },
  bitter: { title: 'Too bitter', actions: ['Identify the cause first: remove over-steeped tea, citrus pith, or burnt pieces.', 'Try a little fat or sweetness in a separate spoonful, then adjust the batch gradually.', 'If bitterness comes from persistent burning or an unknown ingredient, stop and replace the affected food.'], science: 'Fat and sweetness can soften some bitter flavors but cannot repair burned compounds or make unknown ingredients safe.', caution: 'Do not mask bitterness from unidentified plants or suspected spoilage.' },
  underseasoned: { title: 'Bland / under-seasoned', actions: ['Taste a small spoonful and name what is missing: salt, acid, heat, sweetness, or aroma.', 'Add salt a pinch at a time, stir until dissolved, and taste again before adding more. For more heat, add chili in small amounts and let it cook briefly.', 'Brighten with a squeeze of lemon or a splash of vinegar at the end, or finish with fresh herbs or good olive oil.'], science: 'Salt suppresses bitterness and makes aromas more perceptible; acid sharpens flavor contrast. Small additions prevent overshooting, which is much harder to fix than under-seasoning.', caution: 'If the dish will reduce further, season lightly now and adjust at the end.' },
  sweet: { title: 'Too sweet', actions: ['Add unsweetened base or increase the batch with unsweetened ingredients.', 'Test a small amount of acid in a spoonful when appropriate to the dish.', 'Use an unsweetened accompaniment instead of repeatedly adding salt or acid to the whole batch.'], science: 'Dilution reduces sugar concentration. Acidity can balance sweetness perceptually, but the sugar remains.', caution: 'In baking, changing sugar mid-recipe changes moisture and structure; use a less sweet topping or accompaniment.' },
  unknown: { title: 'Pause, isolate, and diagnose', actions: ['Take the pan off heat while you identify the problem.', 'Set aside a small sample to test any correction before changing the batch.', 'Describe the ingredients, technique, timing, and what changed. Choose a matching quick guide or ask your configured model.'], science: 'Heat, concentration, and ingredient ratios determine many texture failures. A small test prevents a mistaken correction from affecting the whole dish.', caution: 'Do not taste food suspected of spoilage, contamination, unsafe storage, or an unknown ingredient. Rescue advice cannot make unsafe food safe.' }
} as const
export type RescueIssue = keyof typeof rescueGuides
export type RescueAdvice = { title: string, actions: string[], science: string, caution: string }
const unsafeSigns = /spoil|mou?ld|unsafe|contaminat|left out|bulg|swell|swollen|fizz|ferment|rancid|slim[ey]|smel\w*\s+(?:off|bad|sour|funny|strange|wrong)|off[-\s]smell|funny smell|expired|past (?:its|the) (?:date|use-by)|botul/
const underseasoned = /\bnot\s+(?:\w+\s+)?(?:salty|spicy|sweet|sour|acidic|seasoned|flavou?rful)\s+enough\b|\bnot enough (?:salt|spice|seasoning|flavou?r)|\bneeds? more (?:salt|seasoning|spice|flavou?r|acid)|\bbland\b|\bunder-?seasoned\b|\btasteless\b|\black(?:s|ing)? flavou?r/
export function rescueTriage(problem: string): RescueAdvice {
  const text = problem.normalize('NFD').replace(/\p{M}/gu, '').toLowerCase()
  // Spoilage signs win over every flavor symptom: those guides suggest tasting.
  const issue: RescueIssue = unsafeSigns.test(text) || /μουχλ|χαλασμ|αλλοιω|ταγγ|ληγμεν|δυσοσμ/.test(text) ? 'unknown'
    : underseasoned.test(text) ? 'underseasoned'
    : /\bgarlic\b|σκορδ/.test(text) && /\b(?:burnt|burned|scorch\w*)\b|καηκ|καμεν|καψαλ|καψ/.test(text) ? 'burnt_garlic'
    : /\bavgolemono\b|\begg[- ]lemon\b|α[υβ]γολεμον/.test(text) && /\b(?:curdl\w*|split|separat\w*|scrambl\w*|broken)\b|εκοψ|κοψει|κομμεν|σβολ|εσπα/.test(text) ? 'avgolemono'
    : /\bbechamel\b|μπεσαμελ/.test(text) && /\b(?:lump\w*|split|separat\w*|broken|curdl\w*)\b|σβολ|κομπ|εκοψ|κοψει|κομμεν|διαχωρ/.test(text) ? 'bechamel_lumpy'
    : /\b(?:moussaka|pastitsio)\b|μουσακ|παστιτσ/.test(text) && /\b(?:watery|runny|soupy|wet)\b|νερ|υγρ|ρευστ/.test(text) ? 'moussaka_watery'
    : /\b(?:lamb|meat|beef|pork|chicken)\b|αρνι|αρνακ|κρεας|κρεατ/.test(text) && /\b(?:dry|dried|tough|overcooked)\b|στεγν|σκληρ|ξεραθ|ξερο/.test(text) ? 'dry_meat'
    : /emulsion|broken sauce|curdl|hollandaise|b[eé]arnaise|vinaigrette|mayo|aioli|\b(?:sauce|dressing|gravy)\b.*\b(?:split|separat)|\b(?:split|separat)\w*\b.*\b(?:sauce|dressing|gravy)\b/.test(text) ? 'emulsion'
      : /salty|oversalt|too much salt/.test(text) ? 'salt'
        : /scorch|burnt|burned/.test(text) ? 'scorch'
          : /soggy|steaming|sear/.test(text) ? 'sear'
            : /acid|sour/.test(text) ? 'acid'
              : /spicy|chilli|chili|too hot/.test(text) ? 'spice'
                : /bitter/.test(text) ? 'bitter' : /sweet|sugar/.test(text) ? 'sweet' : 'unknown'
  const guide = rescueGuides[issue]
  return { ...guide, actions: [...guide.actions] }
}
